#!/bin/bash

# This script copies all the dot files that I want a back up of
# into a folder and backs it up on GitHub.
# Maybe the script should work the other way round i.e. copies to the desired locations (edits get made here first)- so we can have good a commit history.

# Copy .zshrc file here.
cp ~/.zshrc .

# Copy fonts here.
cp -r ~/.fonts/ .

# Copy i3 window manager config files here.
cp -r ~/.config/i3/ .

git add .
git commit -m "dot files backup"
git push
