#!/bin/bash

# This script copies all the dot files that I want a back up of
# into a folder and backs it up on GitHub.
# Maybe the script should work the other way round i.e. copies to the desired
# locations (edits get made here first)- so we can have good a commit history.

# Copy .zshrc file here.
# Note this script does not copy the contents of ~/.oh-my-zsh/
cp ~/.zshrc .

# Copy fonts here.
cp -r ~/.fonts/ .

# Copy i3 window manager config files here.
cp -r ~/.config/i3/ .

# Copy .vimrc file here.
cp ~/.vimrc .

# Copy gtk.css file.
cp ~/.config/gtk-3.0/gtk.css .
